# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 15 Apr 2014 21:09:09 +0000
*               @ALL          1
*               @user         8
