<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: patrick
 * Date: Tue, 15 Apr 2014 22:47:04 +0100
 */

$conf['title'] = 'Bristol Hackspace';
$conf['template'] = 'vector';
$conf['license'] = 'cc-by-sa';
$conf['dmode'] = 02775;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['captcha']['mode'] = 'math';

// end auto-generated content
